<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©英特尔公司</li><li><a href="http://www.miibeian.gov.cn/state/outPortal/loginPortal.action;jsessionid=RRCdPr9GMQw52phdVDPJBJd2cxc8bWvy2HdK9vKvkG0hQygXWqQq!991620579" target="_blank">京 ICP 备 14036123 号-2</a></li><li><a href="https://www.intel.cn/content/www/cn/zh/legal/terms-of-use.html" target="">使用条款</a></li><li><a href="https://www.intel.cn/content/www/cn/zh/legal/trademarks.html" target="">*商标</a></li><li><a href="https://www.intel.cn/content/www/cn/zh/privacy/intel-privacy-notice.html" target="">隐私条款</a></li><li><a href="https://www.intel.cn/content/www/cn/zh/privacy/intel-cookie-notice.html" target="">Cookie</a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/IGHF footer-->