<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel Corporation</li><li><a href="https://www.intel.de/content/www/de/de/legal/terms-of-use.html" target="">Nutzungsbedingungen</a></li><li><a href="https://www.intel.de/content/www/de/de/legal/trademarks.html" target="">*Marken</a></li><li><a href="https://www.intel.de/content/www/de/de/privacy/intel-privacy-notice.html" target="">Sicherheit</a></li><li><a href="https://www.intel.de/content/www/de/de/privacy/intel-cookie-notice.html" target="">Cookies</a></li><li><a href="https://www.intel.de/content/www/de/de/policy/policy-human-trafficking-and-slavery.html" target="">Supply-Chain-Transparenz </a></li><li><a href="https://www.intel.de/content/www/de/de/siteindex.html" target="">Sitemap</a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/IGHF footer-->