<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel 公司</li><li><a href="https://www.intel.com.tw/content/www/tw/zh/legal/terms-of-use.html" target="">使用條款</a></li><li><a href="https://www.intel.com.tw/content/www/tw/zh/legal/trademarks.html" target="">*商標</a></li><li><a href="https://www.intel.com.tw/content/www/tw/zh/privacy/intel-privacy-notice.html" target="">保密政策</a></li><li><a href="https://www.intel.com.tw/content/www/tw/zh/privacy/intel-cookie-notice.html" target="">Cookies</a></li><li><a href="https://www.intel.com.tw/content/www/tw/zh/policy/policy-human-trafficking-and-slavery.html" target="">供應鏈透明 </a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/IGHF footer-->