<!--IGHF footer--> 
<!--GAATversion='50recode' date='09/11/2017 08:00:00' Version='1.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel Corporation</li><li><a href="https://www.intel.vn/content/www/vn/vi/legal/terms-of-use.html" target="">Điều khoản sử dụng</a></li><li><a href="https://www.intel.vn/content/www/vn/vi/legal/trademarks.html" target="">*Thương hiệu</a></li><li><a href="https://www.intel.vn/content/www/vn/vi/privacy/intel-privacy-notice.html" target="">Bảo mật</a></li><li><a href="https://www.intel.vn/content/www/vn/vi/privacy/intel-cookie-notice.html" target="">Cookie</a></li><li><a href="https://www.intel.vn/content/www/vn/vi/policy/policy-human-trafficking-and-slavery.html" target="">Độ minh bạch của chuỗi cung ứng </a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/IGHF footer-->