<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel Corporation</li><li><a href="https://www.intel.co.il/content/www/eu/en/legal/terms-of-use.html" target="">תנאי השימוש</a></li><li><a href="https://www.intel.co.il/content/www/eu/en/legal/trademarks.html" target="">*סימני מסחר</a></li><li><a href="https://www.intel.co.il/content/www/eu/en/privacy/intel-privacy-notice.html" target="">מדיניות פרטיות</a></li><li><a href="https://www.intel.co.il/content/www/eu/en/privacy/intel-cookie-notice.html" target="">קובצי Cookie</a></li><li><a href="https://www.intel.co.il/content/www/eu/en/policy/policy-human-trafficking-and-slavery.html" target="">שקיפות שרשרת האספקה</a></li><li><a href="https://www.intel.co.il/content/www/eu/en/siteindex.html" target="">מפת האתר</a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/IGHF footer-->