<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel Corporation</li><li><a href="https://www.intel.co.id/content/www/id/id/legal/terms-of-use.html" target="">Syarat Penggunaan</a></li><li><a href="https://www.intel.co.id/content/www/id/id/legal/trademarks.html" target="">*Merek Dagang</a></li><li><a href="https://www.intel.co.id/content/www/id/id/privacy/intel-privacy-notice.html" target="">Privasi</a></li><li><a href="https://www.intel.co.id/content/www/id/id/privacy/intel-cookie-notice.html" target="">Cookie</a></li><li><a href="https://www.intel.co.id/content/www/id/id/policy/policy-human-trafficking-and-slavery.html" target="">Transparansi Rantai Pasokan </a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/IGHF footer-->