<!--IGHF Header-->
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<div id="recode50header"></div>
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {};INTELNAV.renderSettings={version:"2.0 - 03/12/2017 08:00:00",textDirection:"ltr",culture:"id_ID",OutputId:"default"};
/*]]>*/</script>
<noscript><link rel="stylesheet" href="https://www.intel.com/ighf/50recode.2/css/ltr_nojsheader.css" type="text/css"><div id="smallfootprint-header"><a class="gaat40-logo" title="Logo - Intel" href="https://www.intel.sg/content/www/xa/en/homepage.html"></a><form method="get" id="user-bar-searchbox-form" name="user-bar-searchbox-form" action="https://www.intel.com/content/www/us/en/search.html"><input id="toplevelcategory" name="toplevelcategory" type="hidden" value="none" tabindex="0"><input id="query" name="query" type="hidden" value="" tabindex="0"><fieldset><legend></legend><label for="input-search">Cari</label><input type="text" id="input-search" name="keyword" tabindex="0" autocomplete="off" /><input type="submit" id="input-submit" name="input-submit" value="Cari" /></fieldset></form></div> </noscript>
<!--/IGHF header-->