<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel Corporation</li><li><a href="https://www.intel.fr/content/www/fr/fr/legal/terms-of-use.html" target="">Conditions d'utilisation</a></li><li><a href="https://www.intel.fr/content/www/fr/fr/legal/trademarks.html" target="">* Marques</a></li><li><a href="https://www.intel.fr/content/www/fr/fr/privacy/intel-privacy-notice.html" target="">Confidentialité</a></li><li><a href="https://www.intel.fr/content/www/fr/fr/privacy/intel-cookie-notice.html" target="">Cookies</a></li><li><a href="/content/www/fr/fr/policy/policy-human-trafficking-and-slavery.html" target="">Transparence de la chaîne logistique </a></li><li><a href="https://www.intel.fr/content/www/fr/fr/siteindex.html" target="">Plan du site</a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/IGHF footer-->