<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel Corporation</li><li><a href="https://www.thailand.intel.com/content/www/th/th/legal/terms-of-use.html" target="">ข้อกำหนดการใช้งาน</a></li><li><a href="https://www.thailand.intel.com/content/www/th/th/legal/trademarks.html" target="">*เครื่องหมายการค้า</a></li><li><a href="https://www.thailand.intel.com/content/www/th/th/privacy/intel-privacy-notice.html" target="">ความเป็นส่วนตัว</a></li><li><a href="https://www.thailand.intel.com/content/www/th/th/privacy/intel-cookie-notice.html" target="">คุ้กกี้</a></li><li><a href="https://www.thailand.intel.com/content/www/th/th/policy/policy-human-trafficking-and-slavery.html" target="">ความโปร่งใสของห่วงโซ่อุปทาน </a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/IGHF footer-->