<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel Corporation</li><li><a href="https://www.intel.com.tr/content/www/tr/tr/legal/terms-of-use.html" target="">Kullanım Koşulları</a></li><li><a href="https://www.intel.com.tr/content/www/tr/tr/legal/trademarks.html" target="">*Ticari Markalar</a></li><li><a href="https://www.intel.com.tr/content/www/tr/tr/privacy/intel-privacy-notice.html" target="">Gizlilik</a></li><li><a href="https://www.intel.com.tr/content/www/tr/tr/privacy/intel-cookie-notice.html" target="">Çerezler</a></li><li><a href="https://www.intel.com.tr/content/www/tr/tr/policy/policy-human-trafficking-and-slavery.html" target="">Tedarik Zinciri Şeffaflığı </a></li><li><a href="https://www.intel.com.tr/content/www/tr/tr/siteindex.html" target="">Site Haritası</a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/footer-->