<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>شركة إنتل ©Intel Corporation</li><li><a href="https://www.intel.com/content/www/xr/ar/legal/terms-of-use.html" target="">شروط الاستخدام</a></li><li><a href="https://www.intel.com/content/www/xr/ar/legal/trademarks.html" target="">*العلامات التجارية</a></li><li><a href="https://www.intel.com/content/www/xr/ar/privacy/intel-privacy-notice.html" target="">الخصوصية</a></li><li><a href="https://www.intel.com/content/www/xr/ar/privacy/intel-cookie-notice.html" target="">ملفات تعريف الارتباط</a></li><li><a href="https://www.intel.com/content/www/xr/ar/policy/policy-human-trafficking-and-slavery.html" target="">شفافية سلسة الإمداد </a></li><li><a href="https://www.intel.com/content/www/xr/ar/siteindex.html" target="">خريطة الموقع</a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/IGHF footer-->