<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel Corporation</li><li><a href="https://www.intel.es/content/www/es/es/legal/terms-of-use.html">Términos de uso</a></li><li><a href="https://www.intel.es/content/www/es/es/legal/trademarks.html">*Marcas comerciales</a></li><li><a href=""></a></li><li><a href="https://www.intel.es/content/www/es/es/privacy/intel-online-privacy-notice-summary.html">Privacidad</a></li><li><a href="https://www.intel.es/content/www/es/es/privacy/intel-cookie-notice.html" target="">Cookies</a></li><li><a href="https://www.intel.es/content/www/es/es/policy/policy-human-trafficking-and-slavery.html" target="">Transparencia de la cadena de suministro </a></li><li><a href="https://www.intel.es/content/www/es/es/siteindex.html" target="">Mapa del sitio</a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/IGHF footer-->