<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel Corporation</li><li><a href="https://www.intel.pl/content/www/pl/pl/legal/terms-of-use.html" target="">Warunki użytkowania</a></li><li><a href="https://www.intel.pl/content/www/pl/pl/legal/trademarks.html" target="">* Znaki towarowe</a></li><li><a href="https://www.intel.pl/content/www/pl/pl/privacy/intel-privacy-notice.html" target="">Ochrona danych</a></li><li><a href="https://www.intel.pl/content/www/pl/pl/privacy/intel-cookie-notice.html" target="">Pliki cookie</a></li><li><a href="https://www.intel.pl/content/www/pl/pl/policy/policy-human-trafficking-and-slavery.html" target="">Przejrzystość łańcucha dostaw </a></li><li><a href="https://www.intel.pl/content/www/pl/pl/siteindex.html" target="">Mapa strony</a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/IGHF footer-->