<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel Corporation</li><li><a href="https://www.intel.la/content/www/xl/es/legal/terms-of-use.html" target="">Términos de uso</a></li><li><a href="https://www.intel.la/content/www/xl/es/legal/trademarks.html" target="">*Marcas comerciales</a></li><li><a href="https://www.intel.la/content/www/xl/es/privacy/intel-privacy-notice.html" target="">Privacidad</a></li><li><a href="https://www.intel.la/content/www/xl/es/privacy/intel-cookie-notice.html" target="">Cookies</a></li><li><a href="https://www.intel.la/content/www/xl/es/policy/policy-human-trafficking-and-slavery.html" target="">Transparencia de la cadena de suministro </a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/IGHF footer-->