<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel Corporation</li><li><a href="https://www.intel.co.uk/content/www/uk/en/legal/terms-of-use.html" target="">Terms of Use</a></li><li><a href="https://www.intel.co.uk/content/www/uk/en/legal/trademarks.html" target="">*Trademarks</a></li><li><a href="https://www.intel.co.uk/content/www/uk/en/privacy/intel-privacy-notice.html" target="">Privacy</a></li><li><a href="https://www.intel.co.uk/content/www/uk/en/privacy/intel-cookie-notice.html" target="">Cookies</a></li><li><a href="https://www.intel.co.uk/content/www/uk/en/policy/policy-human-trafficking-and-slavery.html" target="">Supply Chain Transparency </a></li><li><a href="https://www.intel.co.uk/content/www/uk/en/siteindex.html" target="">Site Map</a></li></ul></div> </noscript>
<div id="recode50footer"></div> 
<!--/IGHF footer-->