<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel Corporation</li><li><a href="https://www.intel.ru/content/www/ru/ru/legal/terms-of-use.html" target="">Условия использования</a></li><li><a href="https://www.intel.ru/content/www/ru/ru/legal/trademarks.html" target="">*Торговые марки</a></li><li><a href="https://www.intel.ru/content/www/ru/ru/privacy/intel-privacy-notice.html" target="">Конфиденциальность</a></li><li><a href="https://www.intel.ru/content/www/ru/ru/privacy/intel-cookie-notice.html" target="">Файлы Cookies</a></li><li><a href="https://www.intel.ru/content/www/ru/ru/policy/policy-human-trafficking-and-slavery.html" target="">Прозрачность цепочки поставок </a></li><li><a href="https://www.intel.ru/content/www/ru/ru/siteindex.html" target="">Карта сайта</a></li></ul></div></noscript>
<div id="recode50footer"></div>
<!--/IGHF footer-->