<script type="text/javascript">
INTELNAV = window.INTELNAV || {};
INTELNAV.dashboard = {
	languageSelector: {
		settings: {
			behavior: "mineOnly",
			method: "path",
			regex: / /
		},
		geos: [
			{ geo: "en_us", path: "onclick='do this'" },
			{ geo: "zh_cn", path: "/zh-cn/" },
			{ geo: "id_id", path: "/id/" },
			{ geo: "ja_jp", path: "/jp/" },
			{ geo: "ko_kr", path: "/ko/" },
			{ geo: "zh_tw", path: "/zh-tw/" },
			{ geo: "es_co", path: "/foo1/" },
			{ geo: "es_mx", path: "/foo2/" },
			{ geo: "es_cl", path: "/foo3/" },
			{ geo: "es_xl", path: "/foo4/" },
			{ geo: "fr_ca", path: "/fr/" }
		]
	}/*,	
	//environment: "qa",
	isVisible: "-footeronly2",
	SSO: {
		mode:"generic",
		signOutPath:"href='javascript:void(0);' onlcick=\"window.location.href=\'/ICS_CommunitySignOutPage?lang=en-US\'\"",
		myProfilePath:"href='https://ssl.intel.com/ipc-app/UserInformation.aspx?lang=ENG'",
		signInPath:"",
		signIn:true
	}*/
};
</script>