<div>
<h3>ASIA</h3>
<a onclick="formatpath('en_AU')" class="en_AU">en_AU</a>
<a onclick="formatpath('en_IN')" class="en_IN">en_IN</a>
<a onclick="formatpath('en_XA')" class="en_XA">en_XA</a>
<a onclick="formatpath('id_ID')" class="id_ID">id_ID</a>
<a onclick="formatpath('ja_JP')" class="ja_JP">ja_JP</a>
<a onclick="formatpath('ko_KR')" class="ko_KR">ko_KR</a>
<a onclick="formatpath('th_TH')" class="th_TH">th_TH</a>
<a onclick="formatpath('vi_VN')" class="vi_VN">vi_VN</a>
<a onclick="formatpath('zh_CN')" class="zh_CN">zh_CN</a>
<a onclick="formatpath('zh_TW')" class="zh_TW">zh_TW</a>
</div>

<div>
<h3>EUROPE</h3>
<a onclick="formatpath('de_DE')" class="de_DE">de_DE</a>
<a onclick="formatpath('en_IE')" class="en_IE">en_IE</a>
<a onclick="formatpath('en_UK')" class="en_UK">en_UK</a>
<a onclick="formatpath('es_ES')" class="es_ES">es_ES</a>
<a onclick="formatpath('fr_FR')" class="fr_FR">fr_FR</a>
<a onclick="formatpath('it_IT')" class="it_IT">it_IT</a>
<a onclick="formatpath('pl_PL')" class="pl_PL">pl_PL</a>
<a onclick="formatpath('ru_RU')" class="ru_RU">ru_RU</a>
<a onclick="formatpath('tr_TR')" class="tr_TR">tr_TR</a>
</div>

<div>
<h3>LATIN AMERICA</h3>
<a onclick="formatpath('es_XL')" class="es_XL">es_XL</a>
<a onclick="formatpath('pt_BR')" class="pt_BR">pt_BR</a>
</div>

<div>
<h3>MIDDLE EAST</h3>
<a onclick="formatpath('ar_XR')" class="ar_XR">ar_XR</a>
<a onclick="formatpath('en_XR')" class="en_XR">en_XR</a>
<a onclick="formatpath('he_IL')" class="he_IL">he_IL</a>
</div>

<div>	
<h3>NORTH AMERICA</h3>	
<a onclick="formatpath('en_CA')" class="en_CA">en_CA</a>
<a onclick="formatpath('en_US')" class="en_US">en_US</a>
<a onclick="formatpath('fr_CA')" class="fr_CA">fr_CA</a>
</div>	