<!--[if IE ]><![endif]-->
<!doctype html>
<!--[if IE 7]>
<html class="rwd no-js vis lt-ie10 lt-ie9 lt-ie8 no-rtl"><![endif]-->
<!--[if IE 8]>
<html class="rwd no-js vis lt-ie10 lt-ie9 no-rtl"><![endif]-->
<!--[if IE 9]>
<html class="rwd no-js vis lt-ie10 no-rtl"><![endif]-->
<!--[if gt IE 9]><!-->
<html class="rwd no-js vis no-rtl"><!--<![endif]-->

<head>	
	<meta charset="UTF-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
	<!--[if lte IE 9]>
		<meta http-equiv="X-UA-Compatible" content="IE=9"/>
	<![endif]-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
	
    <title>uNav Clean - no Subnav</title>
	
	<!--#include virtual="/ighf/50recode.2/prefetch.inc"-->
		
	<!--#include virtual="/ighf/50recode.2/loader2.inc"-->

	<!-- "PUT IGHF DASHBOARD SCRIPT HERE" -->
	<style>body{background-color: #fff;}</style>

	<script type="text/javascript">
	INTELNAV = window.INTELNAV || {};
	INTELNAV.dashboard = {
		languageSelector: {
			settings: {
				behavior: "mineOnly",
				method: "path",
				regex: / /
			},
			geos: [
				{ geo: "en_us", path: "/" },
				{ geo: "zh_cn", path: "/zh-cn/" },
				{ geo: "id_id", path: "/id/" },
				{ geo: "ja_jp", path: "/jp/" },
				{ geo: "ko_kr", path: "/ko/" },
				{ geo: "zh_tw", path: "/zh-tw/" },
				{ geo: "es_co", path: "/foo1/" },
				{ geo: "es_mx", path: "/foo2/" },
				{ geo: "es_cl", path: "/foo3/" },
				{ geo: "es_xl", path: "/foo4/" },
				{ geo: "fr_ca", path: "/fr/" }
			]
		},	
		//environment: "qa",
		isVisible: "-footeronly2"/*,
		SSO: {
			mode:"generic",
			signOutPath:"href='javascript:void(0);' onlcick=\"window.location.href=\'/ICS_CommunitySignOutPage?lang=en-US\'\"",
			myProfilePath:"href='https://ssl.intel.com/ipc-app/UserInformation.aspx?lang=ENG'",
			signInPath:"",
			signIn:true
		}*/
	};
	</script>
	
	<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW, NOSNIPPET, NOIMAGEINDEX"><!-- not needed -->
</head>


<body onload="processPage();" class="recode50">
