/*
 50recode 
 FILE_CHANGED_ON = '2019-03-25 14:15:10'
 VERSION = '1.1.46'
 This source code is property of Intel Corporation.
 DO NOT duplicate, copy or modify this file or any subfiles referenced by this file.
 Please contact the IGHF team if you have issues.
*/
INTELNAV=window.INTELNAV||{};INTELNAV.IGHFRootPath="ighf/50recode.2";INTELNAV.exception=function(e){if(console&&console.log)if(e)console.log(e.stack);else console.log("Argument required when invoking INTELNAV.exception")};
(function(w){var loadCSS=function(href,before,media){var doc=w.document;var ss=doc.createElement("link");var ref;if(before)ref=before;else{var refs=(doc.body||doc.getElementsByTagName("head")[0]).childNodes;ref=refs[refs.length-1]}var sheets=doc.styleSheets;ss.rel="stylesheet";ss.href=href;ss.media="only x";function ready(cb){if(doc.body)return cb();setTimeout(function(){ready(cb)})}ready(function(){ref.parentNode.insertBefore(ss,before?ref:ref.nextSibling)});var onloadcssdefined=function(cb){var resolvedHref=
ss.href;var i=sheets.length;while(i--)if(sheets[i].href===resolvedHref)return cb();setTimeout(function(){onloadcssdefined(cb)})};function loadCB(){if(ss.addEventListener)ss.removeEventListener("load",loadCB);ss.media=media||"all"}if(ss.addEventListener)ss.addEventListener("load",loadCB);ss.onloadcssdefined=onloadcssdefined;onloadcssdefined(loadCB);return ss};if(typeof module!=="undefined"&&module.exports)exports.loadCSS=loadCSS;else w.loadCSS=loadCSS})(typeof global!=="undefined"?global:this);
(function(w){if(!w.loadCSS)return;var rp=loadCSS.relpreload={};rp.support=function(){try{return w.document.createElement("link").relList.supports("preload")}catch(e){return false}};rp.poly=function(){var links=w.document.getElementsByTagName("link");for(var i=0,len=links.length;i<len;i++){var link=links[i];if(link.rel==="preload"&&link.getAttribute("as")==="style"){w.loadCSS(link.href,link,link.getAttribute("media"));link.rel=null}}};if(!rp.support()){rp.poly();var run=w.setInterval(rp.poly,300);
if(w.addEventListener)w.addEventListener("load",function(){rp.poly();w.clearInterval(run)});if(w.attachEvent)w.attachEvent("onload",function(){w.clearInterval(run)})}})(this);var isdebug_bundle_counter=0;
function hf_debug(method,message,obj,debugLvl,isdebug){if(debugLvl<=isdebug&&typeof console!=="undefined"){function indent(counter){var indents="",i=0;for(i=0;i<counter;i++)indents=indents+"\t";return indents}var color=["#FF0000","#FFBF00","#80FF00","#00B359","#00BFFF","#265CFF","#5C26FF","#D24CFF"];var isdebug_indent="";switch(method){case "warn":isdebug_indent=indent(isdebug_bundle_counter);console.warn("%c50recode: "+isdebug_indent+message+obj,"background-color:#cc0000;color:#fff;");break;case "info":isdebug_indent=
indent(isdebug_bundle_counter);console.info("50recode: "+isdebug_indent+message+obj);break;case "error":isdebug_indent=indent(isdebug_bundle_counter);console.error("50recode: "+isdebug_indent+message+obj);break;case "properties":isdebug_indent=indent(isdebug_bundle_counter);console.dir("50recode: "+isdebug_indent+obj);break;case "timestamp":isdebug_indent=indent(isdebug_bundle_counter);if(/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor))console.timeStamp("50recode: "+isdebug_indent+
message);break;case "timestart":isdebug_indent=indent(isdebug_bundle_counter);if(/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor))console.time("50recode: "+isdebug_indent+message);break;case "timeend":isdebug_indent=indent(isdebug_bundle_counter);console.log("50recode: "+isdebug_indent+message+obj);if(/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor))console.timeEnd("50recode: "+isdebug_indent+message);break;case "bundletimestart":isdebug_indent=indent(isdebug_bundle_counter);
console.log("%c50recode: "+isdebug_indent+"START "+message+obj,"color:"+color[isdebug_bundle_counter]+";");console.timeStamp("50recode: "+isdebug_indent+"START "+message);console.time("50recode: "+isdebug_indent+message);isdebug_bundle_counter+=1;break;case "bundletimeend":isdebug_bundle_counter-=1;isdebug_indent=indent(isdebug_bundle_counter);console.log("%c50recode: "+isdebug_indent+"END "+message+obj,"color:"+color[isdebug_bundle_counter]+";");console.timeStamp("50recode: "+isdebug_indent+"END "+
message);console.timeEnd("50recode: "+isdebug_indent+message);break;case "waitfor":isdebug_indent=indent(isdebug_bundle_counter);console.log("%c50recode: "+isdebug_indent+message+obj,"color:#FF0000;");break;default:isdebug_indent=indent(isdebug_bundle_counter);console.log("50recode: "+isdebug_indent+message+obj);break}}}
INTELNAV.getParameterByName=function(name){name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regexS="[\\?&]"+name+"=([^&#]*)";var regex=new RegExp(regexS);var results=regex.exec(window.location.href);if(results===null)return"";else return decodeURIComponent(results[1].replace(/\+/g," "))};
INTELNAV.query=function(){var _query=function(){var results={},q=location.search.replace(/^\?/,"").split("&"),i=0,split={};for(i=0,len=q.length;i<len;i++){split=q[i].split("=");results[split[0]]=split[1]}return results}();return function(name){if(typeof _query[name]==="undefined")return false;else if(_query[name].toLowerCase()=="true")return true;else if(_query[name].toLowerCase()=="false")return false;else return _query[name]}}();
INTELNAV.loadJS=function(filename){hf_debug("log","INTELNAV.loadJS = ",filename,2,isdebug);var fileref=document.createElement("script");fileref.setAttribute("type","text/javascript");fileref.setAttribute("src",filename);fileref.setAttribute("async","");if(typeof fileref!=="undefined")document.getElementsByTagName("head")[0].appendChild(fileref)};INTELNAV.hc=INTELNAV.query("hc");INTELNAV.hcPath=INTELNAV.query("hcpath");
if(INTELNAV.hc&&!INTELNAV.hasrun){INTELNAV.hasrun=true;hf_debug("log","Switch headerchooser.js","",1,isdebug);if(typeof INTELNAV.hc=="boolean")INTELNAV.loadJS("https://localhost/"+INTELNAV.IGHFRootPath+"/js/headerchooser-master.js");else switch(INTELNAV.hc){case "https://www.intel.com":case "https://test-www.intel.com":case "https://ighf-staging.intel.com":case "https://ighf-production.intel.com":case "http://jgarber-mobl.amr.corp.intel.com":case "https://jgarber-mobl.amr.corp.intel.com":case "http://gadev":case "https://gadev":case "https://localhost":INTELNAV.loadJS(INTELNAV.hc+
INTELNAV.hcPath);break;default:hf_debug("info","HC: This path is not approved! ("+INTELNAV.hc+INTELNAV.hcPath+")","",1,isdebug);break}}else{if(INTELNAV.hasrun)hf_debug("log","2nd headerchooser.js","",1,isdebug);(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date;a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","https://www.google-analytics.com/analytics.js",
"ga");ga("create","UA-23487238-1","auto","ighf");ga("ighf.set","anonymizeIp",true);(function(home){hf_debug("bundletimestart","assetLoader-master.js: waitFor()","",2,isdebug);var w={delay:10,_queue:{},_count:0,_lastId:-1,_finalized:false,_log:function(s){if(typeof console!=="undefined"&&typeof console.log!=="undefined")console.log(s)},_timeout:function(){if(w._count>0){var q=w._queue;for(var key in q)if(q.hasOwnProperty(key))if(q[key].t()){hf_debug("log","waitFor: success triggered on entry "+key,
"",2,isdebug);q[key].s();w.remove(key)}}else if(w._finalized){hf_debug("log","waitFor: _timeout() terminating","",2,isdebug);return}w._timeoutId=setTimeout(w._timeout,w.delay)},_init:function(home){hf_debug("log","waitFor: _init() entered (delay:"+w.delay+"ms)","",2,isdebug);if(typeof home==="undefined")home=window;home.waitFor=w;w._timeout()},add:function(test,success){hf_debug("log","waitFor: add("+test+") entered (id:"+(w._lastId+1)+")","",2,isdebug);if(w._finalized){hf_debug("waitfor","waitFor: add("+
test+") attempted after finalize","",2,isdebug);return}w._count+=1;w._lastId+=1;w._queue[w._lastId]={t:test,s:success};return w._lastId},remove:function(id){hf_debug("log","waitFor: remove() entered (id:"+id+")","",2,isdebug);if(w._queue.hasOwnProperty(id)){delete w._queue[id];w._count-=1}},finalize:function(){hf_debug("log","waitFor: finalize() entered","",2,isdebug);w._finalized=true}};w._init(home);hf_debug("bundletimeend","assetLoader-master.js: waitFor()","",2,isdebug)})(window);var wap_header=
{};wap_header.HeaderVersion="";wap_header.HeaderChosen="";wap_header.HeaderSubNav="";wap_header.HeaderGEO="";wap_header.FooterChosen="";wap_header.Locale="";INTELNAV.browserParameters={str:null,bN:null,bM:null,bV:null,OS:null,dT:null,wk:null,bvClass:null};var segment="",searchFilter="",isRWD="false";var isdebug=INTELNAV.getParameterByName("isdebug")||false;hf_debug("info","START HEADERCHOOSER","",2,isdebug);var IE11=INTELNAV.getParameterByName("IE11")||false;var forcetest=INTELNAV.getParameterByName("forcetest");
var menu=0,design=1,env=2;var isMin=".min";hf_debug("log","TEST1","",1,isdebug);window.waitFor.add(function(){return typeof INTELNAV.renderSettings!=="undefined"},function(){window.waitFor.add(function(){return INTELNAV.renderSettings.culture!=="--"},function(){hf_debug("log","WAIT FOR INTELNAV.renderSettings.culture="+INTELNAV.renderSettings.culture,"",1,isdebug);if(typeof INTELNAV.renderSettings!=="undefined")if(typeof INTELNAV.renderSettings.version!=="undefined"){INTELNAV.renderSettings.version=
"2.1 - 05/29/2018 08:00:00";hf_debug("log","SETTING DEFAULT INTELNAV.renderSettings.version="+INTELNAV.renderSettings.version,"",1,isdebug)}if(forcetest!=""&&forcetest.indexOf("-")>=0)INTELNAV.forceTestObj=forcetest.split("-");else{if(typeof INTELNAV.dashboard!=="undefined"&&typeof INTELNAV.dashboard.environment!=="undefined")var tmpForceTest="unav-6-"+INTELNAV.dashboard.environment;else var tmpForceTest="unav-6-prod";hf_debug("log","tmpForceTest="+tmpForceTest,"",1,isdebug);INTELNAV.forceTestObj=
tmpForceTest.split("-")}hf_debug("log","INTELNAV.forceTestObj[]="+INTELNAV.forceTestObj[menu]+"-"+INTELNAV.forceTestObj[design]+"-"+INTELNAV.forceTestObj[env],"",1,isdebug);var RWD=INTELNAV.getParameterByName("RWD")||"";if(RWD!=="")isRWD=RWD;hf_debug("log","RWD="+RWD,"",2,isdebug);if(INTELNAV.getParameterByName("isMin"))isMin="";var disableGA=INTELNAV.getParameterByName("disableGA")||false;var disableWAP=INTELNAV.getParameterByName("disableWAP")||false;var GAAT40=GAAT40||{};GAAT40.renderSettings=
{};GAAT40.renderSettings=INTELNAV.renderSettings;var RollBack=false;INTELNAV.ICP={com:"\u4eac ICP \u5907 14036123 \u53f7-1",cn:"\u6caa ICP \u5907 18006294 \u53f7-1"};INTELNAV.Cultures={unav:{ActiveCulturesFramework:"ar_AE|ar_DZ|ar_EG|ar_MA|ar_SA|ar_XR|cs_CZ|de_CH|de_DE|en_AE|en_AP|en_AU|en_CA|en_EG|en_EU|en_KE|en_HK|en_IE|en_IN|en_IR|en_MY|en_NG|en_NZ|en_PH|en_PK|en_SA|en_SG|en_UK|en_US|en_XA|en_XE|en_XR|en_ZA|es_CL|es_CO|es_ES|es_LA|es_MX|es_XL|fr_CA|fr_DZ|fr_FR|fr_MA|he_IL|hi_IN|hu_HU|id_ID|it_IT|ja_JP|ko_KR|nl_NL|pl_PL|pt_BR|ro_RO|ru_RU|sv_SE|th_TH|tr_TR|uk_UA|vi_VN|zh_CN|zh_TW|fw_FW"}};
INTELNAV.recode50={ighfuat:{design:"ighfuat",firstDesign:6,currentDesign:6,6:{ActiveCultures:"en_US:|nu_LL:",ActiveCultures_RWD:"en_US:|nu_LL:",devPathHttp:"https://localhost/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",stagingPathHttp:"https://ighf-staging.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",testPathHttp:"https://test-www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",preprodPathHttp:"https://ighf-production.intel.com/"+
INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js"}},unav:{design:"unav",firstDesign:6,currentDesign:6,6:{ActiveCultures:"ar_AE:ar_XR|ar_DZ:en_ZA|ar_EG:ar_XR|ar_MA:en_ZA|ar_SA:ar_XR|ar_XR:|cs_CZ:en_US|de_CH:de_DE|de_DE:|en_AE:en_XR|en_AP:en_XA|en_AU:|en_CA:|en_EG:en_XR|en_EU:en_US|en_HK:en_XA|en_IE:|en_IN:|en_IR:en_IE|en_KE:en_ZA|en_MY:en_XA|en_NG:en_ZA|en_NZ:en_AU|en_PH:en_XA|en_PK:en_XA|en_SA:en_XR|en_SG:en_XA|en_UK:|en_US:|en_XA:|en_XE:en_UK|en_XR:|en_ZA:|es_AR:es_XL|es_CL:es_XL|es_CO:es_XL|es_ES:|es_LA:es_XL|es_MX:es_XL|es_XL:|fr_CA:|fr_DZ:en_ZA|fr_FR:|fr_MA:en_ZA|he_IL:|hi_IN:en_IN|hu_HU:en_US|id_ID:|it_IT:|ja_JP:|ko_KR:|nl_NL:en_US|pl_PL:|pt_BR:|ro_RO:en_UK|ru_RU:|sv_SE:en_US|th_TH:|tr_TR:|uk_UA:ru_RU|vi_VN:|zh_CN:|zh_TW:|fw_3R:",
ActiveCultures_RWD:"ar_AE:ar_XR|ar_DZ:en_ZA|ar_EG:ar_XR|ar_MA:en_ZA|ar_SA:ar_XR|ar_XR:|cs_CZ:en_US|de_CH:de_DE|de_DE:|en_AE:en_XR|en_AP:en_XA|en_AU:|en_CA:|en_EG:en_XR|en_EU:en_US|en_HK:en_XA|en_IE:|en_IN:|en_IR:en_IE|en_KE:en_ZA|en_MY:en_XA|en_NG:en_ZA|en_NZ:en_AU|en_PH:en_XA|en_PK:en_XA|en_SA:en_XR|en_SG:en_XA|en_UK:|en_US:|en_XA:|en_XE:en_UK|en_XR:|en_ZA:|es_AR:es_XL|es_CL:es_XL|es_CO:es_XL|es_ES:|es_LA:es_XL|es_MX:es_XL|es_XL:|fr_CA:|fr_DZ:en_ZA|fr_FR:|fr_MA:en_ZA|he_IL:|hi_IN:en_IN|hu_HU:en_US|id_ID:|it_IT:|ja_JP:|ko_KR:|nl_NL:en_US|pl_PL:|pt_BR:|ro_RO:en_UK|ru_RU:|sv_SE:en_US|th_TH:|tr_TR:|uk_UA:ru_RU|vi_VN:|zh_CN:|zh_TW:|fw_3R:",
devPathHttp:"https://localhost/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",stagingPathHttp:"https://ighf-staging.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",testPathHttp:"https://test-www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",preprodPathHttp:"https://ighf-production.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/"+
INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js"}},drc:{design:"drc",firstDesign:6,currentDesign:6,6:{ActiveCultures:"en_US:|nu_LL:",ActiveCultures_RWD:"en_US:|nu_LL:",devPathHttp:"https://localhost/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",stagingPathHttp:"https://ighf-staging.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",testPathHttp:"https://test-www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+
isMin+".js",preprodPathHttp:"https://ighf-production.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js"}},intc:{design:"intc",firstDesign:6,currentDesign:6,6:{ActiveCultures:"en_US:|nu_LL:",ActiveCultures_RWD:"en_US:|nu_LL:",devPathHttp:"https://localhost/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",stagingPathHttp:"https://ighf-staging.intel.com/"+
INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",testPathHttp:"https://test-www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",preprodPathHttp:"https://ighf-production.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js"}},inteldroneracing:{design:"inteldroneracing",firstDesign:6,currentDesign:6,
6:{ActiveCultures:"en_US:|es_XL:|pt_BR:|nu_LL:",ActiveCultures_RWD:"en_US:|es_XL:|pt_BR:|nu_LL:",devPathHttp:"https://localhost/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",stagingPathHttp:"https://ighf-staging.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",testPathHttp:"https://test-www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",preprodPathHttp:"https://ighf-production.intel.com/"+INTELNAV.IGHFRootPath+
"/designs/unav6/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js"}},realsense:{design:"realsense",firstDesign:6,currentDesign:6,6:{ActiveCultures:"en_US:|zh_CN:|nu_LL:",ActiveCultures_RWD:"en_US:|zh_CN:|nu_LL:",devPathHttp:"https://localhost/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",stagingPathHttp:"https://ighf-staging.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+
isMin+".js",testPathHttp:"https://test-www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",preprodPathHttp:"https://ighf-production.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js"}},clusterready:{design:"clusterready",firstDesign:6,currentDesign:6,6:{ActiveCultures:"en_US:|nu_LL:",ActiveCultures_RWD:"en_US:|nu_LL:",
devPathHttp:"https://localhost/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",stagingPathHttp:"https://ighf-staging.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",testPathHttp:"https://test-www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",preprodPathHttp:"https://ighf-production.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/"+
INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js"}},tryoptane:{design:"tryoptane",firstDesign:6,currentDesign:6,6:{ActiveCultures:"en_US:|nu_LL:",ActiveCultures_RWD:"en_US:|nu_LL:",devPathHttp:"https://localhost/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",stagingPathHttp:"https://ighf-staging.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",testPathHttp:"https://test-www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+
isMin+".js",preprodPathHttp:"https://ighf-production.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js"}},chinacampusjobs:{design:"chinacampusjobs",firstDesign:6,currentDesign:6,6:{ActiveCultures:"zh_CN:|nu_LL:",ActiveCultures_RWD:"zh_CN:|nu_LL:",devPathHttp:"https://localhost/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",stagingPathHttp:"https://ighf-staging.intel.com/"+
INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",testPathHttp:"https://test-www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",preprodPathHttp:"https://ighf-production.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js"}},marketingadvisorypanel:{design:"marketingadvisorypanel",firstDesign:6,currentDesign:6,
6:{ActiveCultures:"en_US:|nu_LL:",ActiveCultures_RWD:"en_US:|nu_LL:",devPathHttp:"https://localhost/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",stagingPathHttp:"https://ighf-staging.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",testPathHttp:"https://test-www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",preprodPathHttp:"https://ighf-production.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+
isMin+".js",prodPathHttp:"https://www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js"}},swachhmap:{design:"swachhmap",firstDesign:6,currentDesign:6,6:{ActiveCultures:"en_US:|nu_LL:",ActiveCultures_RWD:"en_US:|nu_LL:",devPathHttp:"https://localhost/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",stagingPathHttp:"https://ighf-staging.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",testPathHttp:"https://test-www.intel.com/"+
INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",preprodPathHttp:"https://ighf-production.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js"}},transportation:{design:"transportation",firstDesign:6,currentDesign:6,6:{ActiveCultures:"en_US:|nu_LL:",ActiveCultures_RWD:"en_US:|nu_LL:",devPathHttp:"https://localhost/"+INTELNAV.IGHFRootPath+
"/designs/unav6/assets/js/assetLoader"+isMin+".js",stagingPathHttp:"https://ighf-staging.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",testPathHttp:"https://test-www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",preprodPathHttp:"https://ighf-production.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+isMin+".js",prodPathHttp:"https://www.intel.com/"+INTELNAV.IGHFRootPath+"/designs/unav6/assets/js/assetLoader"+
isMin+".js"}}};INTELNAV.assetPathHttp="https://www.intel.com";INTELNAV.assetServer="https://www.intel.com";INTELNAV.UrlLookUpTable={urls:[{site:"(cms-|)int-(dev|qa).(altera|intel).com/content/www/[^/]+/[^/]+/programmable/(?!products/reference-designs|products/.*/support.html|products/*/support.html|products.)(products|buy)|www(dev|qa).altera.com/content/www/[^/]+/[^/]+/programmable/(?!products/reference-designs|products/.*/support.html|products/*/support.html|products.)(products|buy)|(qamysupport|mysupport).(altera|intel).com/content/www/[^/]+/[^/]+/programmable/(?!products/reference-designs|products/.*/support.html|products/*/support.html|products.)(products|buy)",
myIntelSignIn:true,searchFilter:[{sf_var:"toplevelcategory",sf_val:"programmable"}]},{site:"(cms-|)int-(dev|qa).(altera|intel).com|www(dev|qa).altera.com|(qamysupport|mysupport|qafpgasupport).(altera|intel).com",myIntelSignIn:true,searchFilter:[{sf_var:"toplevelcategory",sf_val:"PSGSupport"}]},{site:"(www(|.thailand)|fpgasupport).intel.(com|sg|com.au|cn|in|co.id|co.jp|co.kr|com.tw|vn|fr|de|ie|it|pl|ru|es|tr|co.uk|la|com.br|co.za|me|co.il|ca)/content/www/[^/]+/[^/]+/programmable/(?!products/reference-designs|products/.*/support.html|products/*/support.html|products.)(products|buy)",
myIntelSignIn:true,searchFilter:[{sf_var:"toplevelcategory",sf_val:"programmable"}]},{site:"(www(|.thailand)|fpgasupport).intel.(com|sg|com.au|cn|in|co.id|co.jp|co.kr|com.tw|vn|fr|de|ie|it|pl|ru|es|tr|co.uk|la|com.br|co.za|me|co.il|ca)",myIntelSignIn:true,searchFilter:[{sf_var:"toplevelcategory",sf_val:"PSGSupport"}]},{site:"fpgasoftware-test.intel.com",myIntelSignIn:true},{site:"fpgasoftware.intel.com",myIntelSignIn:true},{site:"fpgacloud-test.intel.com",myIntelSignIn:true},{site:"fpgacloud.intel.com",
myIntelSignIn:true},{site:"test.buyfpga.intel.com",myIntelSignIn:true},{site:"buyfpga.intel.com",myIntelSignIn:true},{site:"isvcqa4-intelcustomersupport.cs95.force.com/forums/",myIntelSignIn:true},{site:"forums.intel.com",myIntelSignIn:true},{site:"simplecore-dev.intel.com/drc",menu:"drc",hide:"languageselector"},{site:"drc.intel.com|simplecore(|-dev).intel.com/drc|marketingcentral-dev.intel.com|marketingcentral.intel.com",menu:"drc",hide:"languageselector"},{site:"intel2016ir.q4web.com|www.intc.com",
menu:"intc",hide:"languageselector"},{site:"simplecore-dev.intel.com/inteldroneracing(|-lar|-pt)",menu:"inteldroneracing",env:"staging",hide:"search"},{site:"droneracing.intel(.com|.la|.com.br)",menu:"inteldroneracing",hide:"search"},{site:"modernstandbypartnerportal-dev.apps1-fm-int.icloud.intel.com|modernstandbypartnerportal-preprod.intel.com",myIntelSignIn:true,hide:"menu"},{site:"modernstandbypartnerportal.intel.com",myIntelSignIn:true,hide:"menu"},{site:"simplecore(-dev(|-gar)|-prc).intel.(com|cn)/realsensehub(|-cn)/",
menu:"realsense"},{site:"realsense.intel.(com|cn)",menu:"realsense"},{site:"simplecore-dev.intel.com/clusterready/",menu:"clusterready",hide:"search"},{site:"clusterready.intel.com",menu:"clusterready",hide:"search"},{site:"tryoptane.intel.com",menu:"tryoptane"},{site:"chinacampus.jobs.intel.com",menu:"chinacampusjobs",hide:"languageselector/myintel/search"},{site:"swachhmap.com",menu:"swachhmap"},{site:"transportation.com|transportationdev.intel.com|transportationcons.intel.com",menu:"transportation",
hide:"languageselector|search"},{site:"ccechina.intel.com|ccetest.apicloud-system.com",hide:"menu|languageselector|search|myintel"},{site:"www.cvent.com",hide:"menu|languageselector|search|myintel"},{site:"downloadcenter(01|02|)-(dev|tst|prd|dr).intel.com",searchFilter:[{sf_var:"topicarea",sf_val:"Downloads"}]},{site:"downloadcenter(|-origin).intel.com",searchFilter:[{sf_var:"topicarea",sf_val:"Downloads"}]},{site:"(edc.intel.com|preview-edc.intel.com|inteledcpreviewapp.azurewebsites.net)",searchFilter:[{sf_var:"progId",
sf_val:"irdc"},{sf_var:"EDCProgramIdentifier",sf_val:"true"}]},{site:"(crmdevint2|crmdevmktg|crmqa2)-intelcloudcrm.(cs70|cs93).force.com/partnercenter",hide:"languageselector"},{site:"partnercenter.intel.com",hide:"languageselector"},{site:"processormatch.intel.com|tst1compdb2w01.cps.intel.com|tst1cdb2w.cps.intel.com|tst1cdbmbv2w.cps.intel.com|tst1compdb2w02.cps.intel.com|prd1cdb2w.cps.intel.com|prd1compdb2w01.cps.intel.com|prd1compdb2w02.cps.intel.com"},{site:"(CompDBMBVendor.intel.com|prd1cdbmbv2w.cps.intel.com|prd1cdbmbv2w02.cps.intel.com)"},
{site:"(stg1compdbw01.cps.intel.com|stg1compdbvenw01.cps.intel.com)"},{site:"registrationcenter.intel.com|prd1ircw.cps.intel.com|prd1ircw01.cps.intel.com|prd1ircw02.cps.intel.com|ircutils.cps.intel.com|prd1irciw01.cps.intel.com, prd1irciw02.cps.intel.com|tst1ircw01.cps.intel.com|tst1ircw02.cps.intel.com|ircutils-tst.cps.intel.com|ircutils.intel.com|ircutils-tst.intel.com|tst1irciw01.cps.intel.com|tst1irciw02.cps.intel.com|stg1regcenw01.cps.intel.com|stg1regcenw02.cps.intel.com|stg1regcenw03.cps.intel.com|stg1regcenw04.cps.intel.com|stg1regcenw05.cps.intel.com|stg1regcenw06.cps.intel.com|stg1regcenw07.cps.intel.com|stg1regcenw08.cps.intel.com|stg1regcenw09.cps.intel.com|stg1regcenw10.cps.intel.com|stg1regcenin.cps.intel.com|stg1regcenps.cps.intel.com|nnsapudov001.ccr.corp.intel.com|nnsstrofimo001.ccr.corp.intel.com|inthmemsw01.ccr.corp.intel.com|qs2-registrationcenter.cps.intel.com|registrationcenter.cps.intel.com|registrationcenter-download.intel.com"},
{site:"(isvcqa4-intelcustomersupport.cs95.force.com/onlinecasemgmt|aquiladev4-intelcustomersupport.cs19.force.com/onlinecasemgmt|leodev4-intelcustomersupport.cs19.force.com/onlinecasemgmt|devint4-intelcustomersupport.cs96.force.com/onlinecasemgmt|isvcstage4-intelcustomersupport.cs68.force.com/onlinecasemgmt)",myIntelSignIn:true},{site:"(intelcustomersupport.force.com|customercare.intel.com|supporttickets.intel.com)",myIntelSignIn:true},{site:"nppdevpmp-intelcloudcrm.cs67.force.com",myIntelSignIn:true},
{site:"marketplace.intel.com",myIntelSignIn:true},{site:"(www.|)source.intel.com|sme-intel-preprod.herokuapp.com",hide:"languageselector"},{site:"jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/testharness/50recode.2/*forcetest=drc-4-dev",menu:"drc"},{site:"jgarber-mobl.amr.corp.intel.com/sites/sitewide/HAT/testharness/50recode|ighf-staging.intel.com",design:"6"}]};INTELNAV.oldBrowserDetect=function(){var BrowserMode=document.compatMode=="CSS1Compat"?"Standards":"Quirks";var str=navigator.appVersion.toLowerCase().replace(/[^a-zA-Z 0-9 . / _]+/g,
"").split(" ");deviceType=str[1].substr(0,3);if(/MSIE\s([\d.]+)/.test(navigator.userAgent)){var version=new Number(RegExp.$1);INTELNAV.browser={Name:"ie",Version:version,Mode:BrowserMode};switch(parseInt(version)){case 9:document.documentElement.className+=" lt-ie10";document.body.className+=deviceType+" ie ie9_0";break;case 8:document.documentElement.className+=" lt-ie10 lt-ie9";document.body.className+=deviceType+" ie ie8_0";break;case 7:document.documentElement.className+=" lt-ie10 lt-ie9 lt-ie8";
document.body.className+=deviceType+" ie ie7_0";break;case 6:document.documentElement.className+=" lt-ie10 lt-ie9 lt-ie8 lt-ie7";document.body.className+=deviceType+" ie ie6_0";break;default:break}}else INTELNAV.browser={Name:"",Version:0,Mode:BrowserMode}};INTELNAV.oldBrowserDetect();(function(){hf_debug("timestart","TOTALLOADTIME","",1,isdebug);hf_debug("bundletimestart","headerchooser.js: (function(){})","",2,isdebug);if(INTELNAV.getParameterByName("pageWidth")!=="")INTELNAV.renderSettings.pageWidth=
INTELNAV.getParameterByName("pageWidth");if(INTELNAV.getParameterByName("textDirection")!=="")INTELNAV.renderSettings.textDirection=INTELNAV.getParameterByName("textDirection");if(INTELNAV.getParameterByName("protocol")!=="")INTELNAV.renderSettings.protocol=INTELNAV.getParameterByName("protocol");if(INTELNAV.getParameterByName("culture")!=="")INTELNAV.renderSettings.culture=INTELNAV.getParameterByName("culture");if(INTELNAV.getParameterByName("buildType")!=="")INTELNAV.renderSettings.buildType=INTELNAV.getParameterByName("buildType");
if(INTELNAV.getParameterByName("OutputId")!=="")INTELNAV.renderSettings.OutputId=INTELNAV.getParameterByName("OutputId");INTELNAV.culture=INTELNAV.renderSettings.culture;INTELNAV.baseCulture=INTELNAV.culture;switch(INTELNAV.culture.toUpperCase()){case "EN_XR":case "AR_DZ":case "AR_MA":INTELNAV.renderSettings.textDirection="ltr";break;case "AR_EG":INTELNAV.renderSettings.textDirection="rtl";break;default:break}var outputid=INTELNAV.renderSettings.OutputId;hf_debug("log","CULTURE="+INTELNAV.culture,
"",1,isdebug);hf_debug("log","OUTPUTID="+outputid,"",1,isdebug);hf_debug("log","boxmodel="+document.compatMode,"",1,isdebug);INTELNAV.processUNAVgeos=function(){hf_debug("profile","processUNAVgeos()","",2,isdebug);var getAltGeo=function(thisGeo,listOfGeos){var curGEO=thisGeo;var altGEO="";for(j=0,len=listOfGeos.length;j<len;j++){thisSplitGEO=listOfGeos[j].split(":");if(curGEO==thisSplitGEO[0])if(thisSplitGEO[1]!=null&&thisSplitGEO[1]!="undefined"&&thisSplitGEO[1]!=""){altGEO=thisSplitGEO[1];hf_debug("log",
"ALT CULTURE="+altGEO,"",1,isdebug);break}}return altGEO};INTELNAV.renderSettings.origCulture=INTELNAV.culture;var listOfGeos=INTELNAV.activeCultures.split("|");retGEO=getAltGeo(INTELNAV.renderSettings.culture,listOfGeos);if(retGEO!=""){INTELNAV.culture=retGEO;hf_debug("log","NEW CULTURE="+INTELNAV.culture,"",1,isdebug)}hf_debug("profileEnd","processUNAVgeos()","",2,isdebug)};INTELNAV.initBuild=function(){hf_debug("bundletimestart","headerchooser.js: INTELNAV.initBuild()","",2,isdebug);var currentPageUrl=
document.location.href;var targetEnvironmentForUrl={};var detectIE8=false;INTELNAV.domainLookUp=function(){hf_debug("profile","domainLookUp()","",2,isdebug);var LUT=INTELNAV.UrlLookUpTable.urls;hf_debug("log","forcetest-notempty[1]="+forcetest,"",2,isdebug);var lutlength=LUT.length;if(lutlength>0&&RollBack==false){hf_debug("log","LUT.length="+lutlength,"",2,isdebug);for(var i=0;i<lutlength;i++){var myregexp=new RegExp("^https?:\\/\\/"+LUT[i].site.replace(/\./g,"\\.").replace(/\?(?!!)/g,"\\?").replace(/\*/g,
".+")+".*","i");hf_debug("log","i="+i+"   regex="+myregexp,"",2,isdebug);if(myregexp.test(currentPageUrl)){hf_debug("log","LUT Match Found","",1,isdebug);hf_debug("log","LUT Match Found("+myregexp+")","",2,isdebug);if(!forcetest){if(typeof LUT[i].menu!=="undefined")INTELNAV.forceTestObj[menu]=LUT[i].menu;hf_debug("log","MENU(MAPPED)="+INTELNAV.forceTestObj[menu],"",1,isdebug);if(typeof LUT[i].env!=="undefined")INTELNAV.forceTestObj[env]=LUT[i].env;hf_debug("log","ENVIRONMENT(MAPPED)="+INTELNAV.forceTestObj[env],
"",1,isdebug);if(typeof LUT[i].design!=="undefined")INTELNAV.forceTestObj[design]=parseInt(LUT[i].design);hf_debug("log","DESIGN(MAPPED)="+INTELNAV.forceTestObj[design],"",1,isdebug);hf_debug("log","CULTURE(MAPPED)="+INTELNAV.culture,"",1,isdebug);targetEnvironmentForUrl=LUT[i]}INTELNAV.LUT=LUT[i];window.waitFor.add(function(){return typeof INTELNAV.renderSettingsHeader!=="undefined"},function(){document.getElementById("recode50header").className="recode50unav"});break}}}hf_debug("profileEnd","domainLookUp()",
"",2,isdebug)};if(forcetest==""||forcetest=="empty"||forcetest==null)INTELNAV.domainLookUp();hf_debug("log","INTELNAV.forceTestObj[]="+INTELNAV.forceTestObj[menu]+"-"+INTELNAV.forceTestObj[design]+"-"+INTELNAV.forceTestObj[env],"",2,isdebug);if(!Object.keys)Object.keys=function(){var hasOwnProperty=Object.prototype.hasOwnProperty,hasDontEnumBug=!{toString:null}.propertyIsEnumerable("toString"),dontEnums=["toString","toLocaleString","valueOf","hasOwnProperty","isPrototypeOf","propertyIsEnumerable",
"constructor"],dontEnumsLength=dontEnums.length;return function(obj){if(typeof obj!=="object"&&(typeof obj!=="function"||obj===null))throw new TypeError("Object.keys called on non-object");var result=[],prop,i;for(prop in obj)if(hasOwnProperty.call(obj,prop))result.push(prop);if(hasDontEnumBug)for(i=0;i<dontEnumsLength;i++)if(hasOwnProperty.call(obj,dontEnums[i]))result.push(dontEnums[i]);return result}}();INTELNAV.validateMenu=function(){hf_debug("profile","validateMenu()","",2,isdebug);var menuObj=
INTELNAV.recode50;var tmpMenu=INTELNAV.forceTestObj[menu];var keys=Object.keys(menuObj);var keysLength=keys.length;for(var i=0,keys;i<keysLength;i++){hf_debug("log","validateMenu(): i("+i+") = FOUND ","",2,isdebug);if(keys[i]==INTELNAV.forceTestObj[menu]){hf_debug("log","validateMenu(): iMenu("+keys[i]+") = FOUND "+INTELNAV.recode50[keys[i]],"",2,isdebug);tmpMenu=keys[i];break}else tmpMenu=""}hf_debug("profileEnd","validateMenu()","",2,isdebug);return tmpMenu};INTELNAV.validateDesign=function(){hf_debug("profile",
"validateDesign()","",2,isdebug);var designObj=INTELNAV.recode50[INTELNAV.forceTestObj[menu]];var tmpDesign=-1;var keys=Object.keys(designObj);var keysLength=keys.length;hf_debug("log","validateDesign(): keysLength("+keysLength+");","",2,isdebug);for(var i=0,keys;i<keysLength;i++){hf_debug("log","validateDesign(): i("+INTELNAV.forceTestObj[menu]+");","",2,isdebug);if(keys[i]==INTELNAV.forceTestObj[design]){hf_debug("log","validateDesign(): INTELNAV.forceTestObj[menu]("+INTELNAV.forceTestObj[menu]+
"); iDesign("+keys[i]+") = FOUND "+designObj[keys[i]],"",2,isdebug);tmpDesign=keys[i];break}else tmpDesign=-1}hf_debug("profileEnd","validateDesign()","",2,isdebug);return tmpDesign};INTELNAV.getDesignData=function(){targetEnvironmentForUrl.defaultPathHttp=INTELNAV.recode50[INTELNAV.forceTestObj[menu]][INTELNAV.forceTestObj[design]][INTELNAV.forceTestObj[env]+"PathHttp"];hf_debug("log","getDesignData(): targetEnvironmentForUrl(2).defaultPathHttp="+targetEnvironmentForUrl.defaultPathHttp,"",2,isdebug)};
INTELNAV.designFallbackByGeoMatch=function(){hf_debug("profile","designFallbackByGeoMatch()","",2,isdebug);var count=0;var geoMatch=false;var tmpDesign=INTELNAV.forceTestObj[design];if(INTELNAV.browser.Name=="ie"&&(INTELNAV.browser.Version=="8.0"||INTELNAV.browser.Version=="7.0"||INTELNAV.browser.Version=="6.0")){detectIE8=true;hf_debug("log","detectIE8",detectIE8,1,isdebug)}while(!geoMatch){hf_debug("log","menu="+INTELNAV.forceTestObj[menu],"",2,isdebug);hf_debug("log","tmpDesign="+tmpDesign,"",
2,isdebug);hf_debug("log","INTELNAV.Cultures="+INTELNAV.recode50[INTELNAV.forceTestObj[menu]][tmpDesign],"",2,isdebug);hf_debug("log","firstDesign="+parseInt(INTELNAV.recode50[INTELNAV.forceTestObj[menu]]["firstDesign"]),"",2,isdebug);if(typeof INTELNAV.recode50[INTELNAV.forceTestObj[menu]][tmpDesign]!=="undefined")if(typeof INTELNAV.recode50[INTELNAV.forceTestObj[menu]][tmpDesign]["ActiveCultures"]!=="undefined"){INTELNAV.activeCultures=INTELNAV.recode50[INTELNAV.forceTestObj[menu]][tmpDesign]["ActiveCultures"];
INTELNAV.processUNAVgeos();hf_debug("log","parseInt(INTELNAV.recode50[INTELNAV.forceTestObj[menu]][tmpDesign]['ActiveCultures']['firstDesign'])",INTELNAV.recode50[INTELNAV.forceTestObj[menu]]["firstDesign"],2,isdebug);if(INTELNAV.recode50[INTELNAV.forceTestObj[menu]][tmpDesign]["ActiveCultures"].search(INTELNAV.culture)!==-1){geoMatch=true;hf_debug("log","designFallbackByGeoMatch(A)="+tmpDesign,"",2,isdebug);hf_debug("log","DESIGN("+tmpDesign+")=GEO("+INTELNAV.culture+") Match Found!","",1,isdebug)}else if(tmpDesign==
parseInt(INTELNAV.recode50[INTELNAV.forceTestObj[menu]]["firstDesign"])){INTELNAV.culture="en_US";tmpDesign=INTELNAV.forceTestObj[design];geoMatch=true;hf_debug("log","designFallbackByGeoMatch(B)="+tmpDesign,"",2,isdebug);hf_debug("log","##teamcity[message text='GEO("+INTELNAV.baseCulture+") not found in DESIGN("+tmpDesign+")' errorDetails='GEO("+INTELNAV.baseCulture+") not found in DESIGN("+tmpDesign+")' status='FAILURE'] ","",1,isdebug);hf_debug("log","Resetting to DESIGN("+tmpDesign+"), GEO("+
INTELNAV.culture+") ","",1,isdebug)}else{tmpDesign--;hf_debug("log","designFallbackByGeoMatch(C)="+tmpDesign,"",1,isdebug);hf_debug("log","##teamcity[message text='GEO("+INTELNAV.baseCulture+") not found in DESIGN("+tmpDesign+"), falling back' errorDetails='GEO("+INTELNAV.baseCculture+") not found in DESIGN("+tmpDesign+"), falling back' status='FAILURE'] ","",1,isdebug);hf_debug("log","DESIGN("+tmpDesign+")=GEO("+INTELNAV.culture+") Not Found, falling back","",1,isdebug)}}else tmpDesign--;else tmpDesign--;
count++;if(count>20){geoMatch=true;hf_debug("log","designFallbackByGeoMatch(>10)="+tmpDesign,"",2,isdebug)}}INTELNAV.forceTestObj[design]=tmpDesign;hf_debug("profileEnd","designFallbackByGeoMatch()","",2,isdebug)};hf_debug("log","MENU(MAPPED2)="+INTELNAV.forceTestObj[menu],"",1,isdebug);hf_debug("log","DESIGN(MAPPED2)="+INTELNAV.forceTestObj[design],"",1,isdebug);hf_debug("log","CULTURE(MAPPED2)="+INTELNAV.culture,"",1,isdebug);if(typeof INTELNAV.recode50[INTELNAV.forceTestObj[menu]]!=="undefined"){hf_debug("log",
"INTELNAV.forceTestObj[menu]("+INTELNAV.forceTestObj[menu]+") = VALID","",1,isdebug);if((INTELNAV.forceTestObj[design]=INTELNAV.validateDesign())>=0){hf_debug("log","INTELNAV.forceTestObj[design]("+INTELNAV.forceTestObj[design]+") = VALID","",2,isdebug);INTELNAV.designFallbackByGeoMatch();hf_debug("log","MENU(MAPPED3)="+INTELNAV.forceTestObj[menu],"",1,isdebug);hf_debug("log","DESIGN(MAPPED3)="+INTELNAV.forceTestObj[design],"",1,isdebug);hf_debug("log","CULTURE(MAPPED3)="+INTELNAV.culture,"",1,isdebug);
INTELNAV.getDesignData();switch(INTELNAV.forceTestObj[menu]){case "drc":case "intc":case "unav":default:hf_debug("log","forcetest-design[3+4]="+forcetest,"",2,isdebug);if(INTELNAV.browser.Name=="ie"&&INTELNAV.browser.Version=="7.0"){detectIE8=true;hf_debug("log","detectIE8",detectIE8,1,isdebug);hf_debug("log","enable HTML5 objects for IE8","",1,isdebug);document.createElement("header");document.createElement("section");document.createElement("article");document.createElement("aside");document.createElement("nav");
document.createElement("footer")}if(INTELNAV.recode50[INTELNAV.forceTestObj[menu]][INTELNAV.forceTestObj[design]]["ActiveCultures"].toUpperCase().search(INTELNAV.culture)!==-1&&detectIE8==false){hf_debug("log","DESIGN(INIT)="+INTELNAV.forceTestObj[design],"",2,isdebug);if(typeof INTELNAV.dashboard!=="undefined"&&typeof INTELNAV.dashboard.isVisible!=="undefined")segment=INTELNAV.dashboard.isVisible;if(typeof targetEnvironmentForUrl.isVisible!=="undefined")segment="-"+targetEnvironmentForUrl.isVisible;
if(segment=="-footeronly"){document.getElementById("recode50header").className+=" u-nav-hidden ";document.getElementById("recode50header").style.display="none";window.waitFor.add(function(){return typeof INTELNAV.renderSettingsFooter!=="undefined"},function(){document.getElementById("recode50footer").className+=" small "})}else segment="-both";hf_debug("log","SEGMENT="+segment,"",1,isdebug);INTELNAV.activeCultures=INTELNAV.recode50[INTELNAV.forceTestObj[menu]][INTELNAV.forceTestObj[design]]["ActiveCultures_RWD"]}if(!forcetest){if(typeof INTELNAV.LUT!==
"undefined")if(typeof INTELNAV.LUT.searchFilter!=="undefined")searchFilter=INTELNAV.LUT.searchFilter;if(typeof targetEnvironmentForUrl.searchFilter!=="undefined")searchFilter=targetEnvironmentForUrl.searchFilter;hf_debug("log","searchFilter="+searchFilter,"",2,isdebug)}isRWD="true";break}INTELNAV.renderSettings.culture=INTELNAV.culture;INTELNAV.assetPathHttp=targetEnvironmentForUrl.defaultPathHttp;hf_debug("log","INTELNAV.assetPathHttp="+INTELNAV.assetPathHttp,"",2,isdebug);assetPath=INTELNAV.assetPathHttp;
var rx;rx=/(https?:\/\/[-\w.]+)+(:\d+)?(\/)?/;matches=assetPath.match(rx);if(matches!==null){host=matches[0];if(host.charAt(host.length-1)=="/")host=host.slice(0,-1)}INTELNAV.assetServer=host;hf_debug("log","INTELNAV.assetServer="+INTELNAV.assetServer,"",2,isdebug);hf_debug("log","INTELNAV.loadJS(assetPath)","",2,isdebug);INTELNAV.loadJS(assetPath);hf_debug("bundletimeend","headerchooser.js: INTELNAV.initBuild()","",2,isdebug)}else hf_debug("log","INTELNAV.forceTestObj[design]("+INTELNAV.forceTestObj[design]+
") = NOT FOUND ","",2,isdebug)}else hf_debug("log","INTELNAV.forceTestObj[menu]("+INTELNAV.forceTestObj[menu]+") = NOT FOUND ","",2,isdebug);hf_debug("log","======================================","",2,isdebug)};INTELNAV.initBuild();hf_debug("log","testtest","",2,isdebug);window.waitFor.add(function(){return typeof INTELNAV.renderSettingsFooter!=="undefined"},function(){hf_debug("log","waitFor: typeof INTELNAV.renderSettingsFooter.OutputId !== 'undefined'","",2,isdebug);var HeaderType=INTELNAV.forceTestObj[menu]+
INTELNAV.forceTestObj[design]+INTELNAV.forceTestObj[env];if(document.compatMode=="BackCompat")HeaderType=HeaderType+"(Quirks)";if(INTELNAV.renderSettings.protocol=="https")HeaderType=HeaderType+"("+INTELNAV.renderSettings.protocol.toUpperCase()+")";hf_debug("log","HeaderType="+HeaderType,"",1,isdebug);if(typeof INTELNAV.renderSettings.version!=="undefined"){var patrn=/\d+(\.\d+)+/g;var str=INTELNAV.renderSettings.version;var myArray=str.match(patrn);var frameworkShortVersion=myArray[0]}else frameworkShortVersion=
"2.x";hf_debug("log","frameworkShortVersion="+frameworkShortVersion,"",1,isdebug);hf_debug("log","50recode."+frameworkShortVersion,"",1,true);ga("ighf.set","dimension1","50recode."+frameworkShortVersion);ga("ighf.set","dimension2",INTELNAV.renderSettings.version);ga("ighf.set","dimension3",HeaderType);ga("ighf.set","dimension4",outputid);ga("ighf.set","dimension5",INTELNAV.culture);ga("ighf.set","dimension6",INTELNAV.renderSettingsFooter.OutputId);ga("ighf.set","dimension7","renderMode:"+INTELNAV.renderSettings.renderMode+
".protocol:"+INTELNAV.renderSettings.protocol+".pageWidth:"+INTELNAV.renderSettings.pageWidth+".INT.50recode");if(!disableGA)ga("ighf.send","pageview");if(!disableGA){wap_header.HeaderVersion="50recode."+frameworkShortVersion;wap_header.HeaderChosen=HeaderType;wap_header.HeaderSubNav=outputid;wap_header.HeaderGEO=INTELNAV.culture;wap_header.FooterChosen=INTELNAV.renderSettingsFooter.OutputId;wap_header.RenderSettings="version:"+INTELNAV.renderSettings.version+".textDirection:"+INTELNAV.renderSettings.textDirection+
".OutputId:"+INTELNAV.renderSettings.OutputId;var lang_sel=INTELNAV.culture;var tms_loc=lang_sel==="undefined"?"en_us":lang_sel.toLowerCase();var strLocale=tms_loc.split("_");var wa_country=strLocale[1];var wa_language=strLocale[0];wap_header.Locale=wa_country+"-"+wa_language;wap_header.waGetCookieVal=function(offset){var endstr=document.cookie.indexOf(";",offset);if(endstr==-1)endstr=document.cookie.length;return unescape(document.cookie.substring(offset,endstr))};wap_header.waGetCookie=function(name){var arg=
name+"=";var alen=arg.length;var clen=document.cookie.length;var i=0;while(i<clen){var j=i+alen;if(document.cookie.substring(i,j)==arg)return wap_header.waGetCookieVal(j);i=document.cookie.indexOf(" ",i)+1;if(i==0)break}return null};hf_debug("log","WAP load","",1,isdebug);window.addEventListener("load",function(){hf_debug("log","WAP load 1","",1,isdebug);if(typeof wap_header!=="undefined"&&(typeof wap_tms==="undefined"||typeof wap_tms.unavLoad==="undefined")){hf_debug("log","WAP load 2","",1,isdebug);
setTimeout(function(){hf_debug("log","WAP load 3","",1,isdebug);if(typeof wap_tms==="undefined"||typeof wap_tms.unavLoad==="undefined"){hf_debug("log","WAP load 4a - trigger GA Image tag","",1,isdebug);var img=document.createElement("img");var cid=wap_header.waGetCookie("gawap")?wap_header.waGetCookie("gawap").substring(6):"";cid=cid!==""?cid:wap_header.waGetCookie("_ga")?wap_header.waGetCookie("_ga").substring(6):"";var rand_num=Math.floor(Math.random()*1E4);cid=cid!==""?cid:"833840097.148311"+rand_num;
img.src="https://www.google-analytics.com/collect?v=1&t=pageview&tid=UA-35949610-2&cid="+cid+"&dp="+location.pathname+"&dl="+document.location.href.split("?")[0]+"&cd1=asmo-na&cd2=us-en&cd3=header-footer-img&cd50="+wap_header.HeaderVersion+"&cd51="+wap_header.HeaderChosen+"&cd52="+wap_header.HeaderSubNav+"&cd53="+wap_header.HeaderGEO+"&cd54="+wap_header.FooterChosen+"&cd98="+wap_header.RenderSettings+"&cd99="+wap_header.Locale;document.body.appendChild(img)}else if(!wap_tms.unavLoad){hf_debug("log",
"WAP load 4b - trigger GA Image tag","",1,isdebug);var img=document.createElement("img");var cid=wap_header.waGetCookie("gawap")?wap_header.waGetCookie("gawap").substring(6):"";cid=cid!==""?cid:wap_header.waGetCookie("_ga")?wap_header.waGetCookie("_ga").substring(6):"";var rand_num=Math.floor(Math.random()*1E4);cid=cid!==""?cid:"833840097.148311"+rand_num;img.src="https://www.google-analytics.com/collect?v=1&t=pageview&tid=UA-35949610-2&cid="+cid+"&dp="+location.pathname+"&dl="+document.location.href.split("?")[0]+
"&cd1=asmo-na&cd2=us-en&cd3=header-footer-img&cd50="+wap_header.HeaderVersion+"&cd51="+wap_header.HeaderChosen+"&cd52="+wap_header.HeaderSubNav+"&cd53="+wap_header.HeaderGEO+"&cd54="+wap_header.FooterChosen+"&cd98="+wap_header.RenderSettings+"&cd99="+wap_header.Locale;document.body.appendChild(img)}},500)}})}});hf_debug("bundletimeend","headerchooser.js: (function(){})","",2,isdebug)})()})});function sectionOn(){}function hideAllMenus(){}function writeMenus(){}};
