<!--IGHF footer--> 
<!--GAATversion='50recode.2' date='09/11/2017 08:00:00' Version='2.0':CharacterEncoding:utf8--> 
<script type="text/javascript">
/*<![CDATA[*/
INTELNAV = window.INTELNAV || {}; INTELNAV.renderSettingsFooter={version:"2.0 - 03/12/2017 08:00:00",OutputId:"gf_default"};
/*]]>*/</script> 
<noscript><div id="smallfootprint-footer"><ul><li>©Intel Corporation</li><li><a href="https://www.intel.it/content/www/it/it/legal/terms-of-use.html" target="">Termini di utilizzo</a></li><li><a href="https://www.intel.it/content/www/it/it/legal/trademarks.html" target="">*Marchi</a></li><li><a href="https://www.intel.it/content/www/it/it/privacy/intel-privacy-notice.html" target="">Privacy</a></li><li><a href="https://www.intel.it/content/www/it/it/privacy/intel-cookie-notice.html" target="">Cookie</a></li><li><a href="https://www.intel.it/content/www/it/it/policy/policy-human-trafficking-and-slavery.html" target="">Trasparenza nella catena di fornitura </a></li><li><a href="https://www.intel.it/content/www/it/it/siteindex.html" target="">Mappa del sito</a></li></ul></div> </noscript>
<div id="recode50footer"> </div> 
<!--/IGHF footer-->